name: 'Build Docker Image'
description: 'Builds and optionally pushes a Docker image'
inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  image_tag:
    description: 'Docker image tag'
    required: true
  push_image:
    description: 'Whether to push the image to DockerHub'
    default: 'false'
  dockerhub_username:
    description: 'DockerHub username if pushing'
  dockerhub_password:
    description: 'DockerHub password if pushing'
  optimize_space:
    description: 'Whether to maximize build space'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Maximize build space
      if: inputs.optimize_space == 'true'
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 35000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Checkout code
      if: inputs.optimize_space == 'true'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: inputs.push_image == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push_image }}
        tags: ${{ inputs.image_tag }}
        context: "."
        file: ${{ inputs.dockerfile }}
