name: Docker Image CI GPU

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: ./.github/actions/docker-build.yml
        with:
          dockerfile: "dockerfile.gpu"
          image_tag: "gretelxai/gretel:gpu-latest"
          push_image: ${{ github.event_name == 'push' }}
          optimize_space: "false"
